In [2]:
from kmcpy.external.pymatgen_structure import Structure

prim_bulk=Structure.from_cif("EntryWithCollCode15546_Na4Zr2Si3O12_573K.cif")
supercell=prim_bulk.make_kmc_supercell([3,2,1])



print(supercell)

for i in range(0,len(supercell._sites)):
    print(supercell._sites[i],supercell.sites[i])

Full Formula (Na144 Zr72 Si108 O432)
Reduced Formula: Na4Zr2(SiO4)3
abc   :  27.558900  18.372600  22.181000
angles:  90.000000  90.000000 120.000000
Sites (756)
  #  SP           a         b         c  label      local_index  supercell      wyckoff_sequence
---  ----  --------  --------  --------  -------  -------------  -----------  ------------------
  0  Na+   0         0         0.5       Na1                 12  (0, 0, 0)                     0
  1  Na+   1         0.5       0.5       Na1                 12  (0, 1, 0)                     0
  2  Na+   0.333333  0         0.5       Na1                 12  (1, 0, 0)                     0
  3  Na+   0.333333  0.5       0.5       Na1                 12  (1, 1, 0)                     0
  4  Na+   0.666667  0         0.5       Na1                 12  (2, 0, 0)                     0
  5  Na+   0.666667  0.5       0.5       Na1                 12  (2, 1, 0)                     0
  6  Na+   0         0         0         Na1                 1

In [8]:
def test_neighbor_info_matcher():
    print("neighbor info matcher testing")
 
    from kmcpy.event_generator import generate_events3,neighbor_info_matcher
    import numpy as np

    from kmcpy.external.pymatgen_structure import Structure
    from kmcpy.external.pymatgen_local_env import CutOffDictNN

    nasicon=Structure.from_cif("EntryWithCollCode15546_Na4Zr2Si3O12_573K.cif",primitive=True)

    center_Na1=[0,1]
    local_env_finder = CutOffDictNN({('Na+','Na+'):4,('Na+','Si4+'):4})


    reference_neighbor_sequences=sorted(sorted(local_env_finder.get_nn_info(nasicon,center_Na1[0]),key=lambda x:x["wyckoff_sequence"]),key = lambda x:x["label"])     

    np.set_printoptions(precision=2,suppress=True)
    reference_neighbor=neighbor_info_matcher.from_neighbor_sequences(neighbor_sequences=reference_neighbor_sequences)


    print(reference_neighbor.neighbor_species)
    print(reference_neighbor.distance_matrix)
    print(neighbor_info_matcher.build_angle_matrix_from_getnninfo_output(reference_neighbor_sequences))

    wrong_sequence_neighbor=sorted(sorted(local_env_finder.get_nn_info(nasicon,center_Na1[1]),key=lambda x:x["wyckoff_sequence"]),key = lambda x:x["label"]) 
    
    print(reference_neighbor_sequences,wrong_sequence_neighbor)
    print(type(wrong_sequence_neighbor),type(reference_neighbor_sequences))
    
    print("this should be False",np.allclose(neighbor_info_matcher.build_angle_matrix_from_getnninfo_output(reference_neighbor_sequences),neighbor_info_matcher.build_angle_matrix_from_getnninfo_output(wrong_sequence_neighbor)))
    
    resorted_wrong_sequence=reference_neighbor.brutal_match(wrong_sequence_neighbor,rtol=0.01)
    
    resorted_neighbor=neighbor_info_matcher.from_neighbor_sequences(neighbor_sequences=resorted_wrong_sequence)
    
    print("this should be True",np.allclose(neighbor_info_matcher.build_angle_matrix_from_getnninfo_output(reference_neighbor_sequences),neighbor_info_matcher.build_angle_matrix_from_getnninfo_output(resorted_wrong_sequence)))
    
test_neighbor_info_matcher()


new sorting is found,new distance matrix is 
[[0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [5.1  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [5.1  5.1  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [4.73 6.96 4.73 0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [4.73 4.73 6.96 5.1  0.   0.   0.   0.   0.   0.   0.   0.  ]
 [6.96 4.73 4.73 5.1  5.1  0.   0.   0.   0.   0.   0.   0.  ]
 [3.16 6.2  3.06 3.71 6.54 6.49 0.   0.   0.   0.   0.   0.  ]
 [3.06 3.16 6.2  6.49 3.71 6.54 5.63 0.   0.   0.   0.   0.  ]
 [6.2  3.06 3.16 6.54 6.49 3.71 5.63 5.63 0.   0.   0.   0.  ]
 [6.54 6.49 3.71 3.16 6.2  3.06 4.92 7.48 4.92 0.   0.   0.  ]
 [3.71 6.54 6.49 3.06 3.16 6.2  4.92 4.92 7.48 5.63 0.   0.  ]
 [6.49 3.71 6.54 6.2  3.06 3.16 7.48 4.92 4.92 5.63 5.63 0.  ]]
The differece matrix is : 

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -0. -0.  0.

neighbor info matcher testing
(('Na+', 6), ('Si4+', 6))
[[0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [5.1  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [5.1  5.1  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [4.73 6.96 4.73 0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [4.73 4.73 6.96 5.1  0.   0.   0.   0.   0.   0.   0.   0.  ]
 [6.96 4.73 4.73 5.1  5.1  0.   0.   0.   0.   0.   0.   0.  ]
 [3.16 6.2  3.06 3.71 6.54 6.49 0.   0.   0.   0.   0.   0.  ]
 [3.06 3.16 6.2  6.49 3.71 6.54 5.63 0.   0.   0.   0.   0.  ]
 [6.2  3.06 3.16 6.54 6.49 3.71 5.63 5.63 0.   0.   0.   0.  ]
 [6.54 6.49 3.71 3.16 6.2  3.06 4.92 7.48 4.92 0.   0.   0.  ]
 [3.71 6.54 6.49 3.06 3.16 6.2  4.92 4.92 7.48 5.63 0.   0.  ]
 [6.49 3.71 6.54 6.2  3.06 3.16 7.48 4.92 4.92 5.63 5.63 0.  ]]
[[[ 0.    0.    0.   ...  0.    0.    0.  ]
  [ 0.    0.    0.   ...  0.    0.    0.  ]
  [ 0.    0.    0.   ...  0.    0.    0.  ]
  ...
  [ 0.    0.    0.   ...  0.    0.    0.  ]
  [ 0