In [2]:
from kmcpy.external.pymatgen_structure import Structure

prim_bulk=Structure.from_cif("EntryWithCollCode15546_Na4Zr2Si3O12_573K.cif")
supercell=prim_bulk.make_kmc_supercell([3,2,1])



print(supercell)

for i in range(0,len(supercell._sites)):
    print(supercell._sites[i],supercell.sites[i])

Full Formula (Na144 Zr72 Si108 O432)
Reduced Formula: Na4Zr2(SiO4)3
abc   :  27.558900  18.372600  22.181000
angles:  90.000000  90.000000 120.000000
Sites (756)
  #  SP           a         b         c  label      local_index  supercell      wyckoff_sequence
---  ----  --------  --------  --------  -------  -------------  -----------  ------------------
  0  Na+   0         0         0.5       Na1                 12  (0, 0, 0)                     0
  1  Na+   1         0.5       0.5       Na1                 12  (0, 1, 0)                     0
  2  Na+   0.333333  0         0.5       Na1                 12  (1, 0, 0)                     0
  3  Na+   0.333333  0.5       0.5       Na1                 12  (1, 1, 0)                     0
  4  Na+   0.666667  0         0.5       Na1                 12  (2, 0, 0)                     0
  5  Na+   0.666667  0.5       0.5       Na1                 12  (2, 1, 0)                     0
  6  Na+   0         0         0         Na1                 1

In [3]:

from kmcpy.io import InputSet,load_occ
from kmcpy.kmc import KMC
api=2
inputset=InputSet.from_json("input/test_input_v3.json",api=2)

print(inputset._parameters.keys())
print(inputset._parameters["mc_results"])
inputset.parameter_checker()

inputset.set_parameter("occ",load_occ(fname=inputset._parameters["mc_results"],shape=inputset._parameters["supercell_shape"],select_sites=inputset._parameters["select_sites"],api=inputset.api,verbose=True))
kmc = KMC(api=api)
events_initialized = kmc.initialization(**inputset._parameters) # v in 10^13 hz

# # step 2 compute the site kernal (used for kmc run)
kmc.load_site_event_list(inputset._parameters["event_kernel"])

# # step 3 run kmc
tracker=kmc.run_from_database(events=events_initialized,**inputset._parameters)
print(tracker.return_current_info())
import numpy as np
print(np.array((3.517242770690013e-06, 26.978226076495748, 3.187544456106211e-10, 1.2783794881088614e-10, 0.025760595723683707, 0.4010546380490277, 0.04309185078659044)))


dict_keys(['v', 'equ_pass', 'kmc_pass', 'supercell_shape', 'fitting_results', 'fitting_results_site', 'lce_fname', 'lce_site_fname', 'prim_fname', 'event_fname', 'event_kernel', 'mc_results', 'select_sites', 'T', 'comp', 'structure_idx', 'api', 'immutable_sites', 'verbose', 'random_seed', 'use_numpy_random_kernel', 'convert_to_primitive_cell'])
./input/initial_state.json
verbose output is enabled, this is function io.load_acc from Api2
selected sites are [0, 1, 2, 3, 4, 5, 6, 7, 12, 13, 14, 15, 16, 17]
converting the occupation raw data to dimension: (42, 2, 1, 1)
occupation_chebyshev: [-1 -1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1  1 -1 -1  1 -1 -1 -1
 -1 -1 -1 -1]
Initializing kMC calculations with pirm.cif at ./input/EntryWithCollCode15546_Na4Zr2Si3O12_573K.cif ...
Supercell Shape:
 [[2 0 0]
 [0 1 0]
 [0 0 1]]
Converting to the supercell ...
removing the immutable sites: ['Zr', 'O', 'Zr4+', 'O2-']
Loading fitting results E_kra...
Loading fitting results (site energy or E_end) .

/Users/weihangxie/Documents/GitHub/kmcPy_dev/kmcpy/tracker.py:93: RuntimeWarning: invalid value encountered in true_divide
  corr_factor = np.linalg.norm(self.displacement,axis=1)**2/(self.hop_counter*a**2)


52	1.816E-06	1.643E+01	4.878E-11	1.507E-10	3.942E-03	3.090E+00	5.921E-02	0.29	0.24
53	1.846E-06	1.847E+01	4.799E-11	1.667E-10	3.878E-03	3.474E+00	6.029E-02	0.29	0.24
54	1.869E-06	1.815E+01	4.974E-11	1.618E-10	4.020E-03	3.254E+00	5.976E-02	0.29	0.24
55	1.882E-06	1.867E+01	1.647E-11	1.654E-10	1.331E-03	1.004E+01	6.020E-02	0.29	0.24
56	1.907E-06	1.561E+01	1.625E-11	1.365E-10	1.314E-03	8.395E+00	5.765E-02	0.29	0.24
57	1.930E-06	1.561E+01	1.606E-11	1.349E-10	1.298E-03	8.395E+00	5.750E-02	0.29	0.24
58	1.981E-06	2.089E+01	3.624E-10	1.758E-10	2.928E-02	4.851E-01	3.716E-02	0.29	0.24
59	2.021E-06	1.938E+01	2.866E-10	1.598E-10	2.316E-02	5.575E-01	5.920E-02	0.29	0.24
60	2.039E-06	2.192E+01	3.533E-10	1.792E-10	2.855E-02	5.072E-01	6.048E-02	0.29	0.24
61	2.086E-06	2.006E+01	2.588E-10	1.603E-10	2.091E-02	6.194E-01	5.927E-02	0.29	0.24
62	2.126E-06	1.938E+01	2.726E-10	1.520E-10	2.203E-02	5.575E-01	5.857E-02	0.29	0.24
63	2.163E-06	2.192E+01	3.330E-10	1.689E-10	2.691E-02	5.072E-01	5.987E-02	0.29	0.24
64	2