no sys args version, for debug purpose

Following block are complete process for running KMC on API=1, from generating input files to run the kernel, Always run it see if it works after make modification on code.


following block is for generating the local cluster expansion model. See the Table S3 in support information of nasicon kmc as reference

The localclusterexpansion.initialization is for generating the **lce.json and lcesite.json**

In [7]:
from kmcpy.model import LocalClusterExpansion

a=LocalClusterExpansion(api=1)
a.initialization1(center_Na1_index=0,cutoff_cluster=[6,6,0],cutoff_region=4,template_cif_fname='./EntryWithCollCode15546_Na4Zr2Si3O12_573K.cif')
a.to_json("lce.json")

Searching local env around [ 0.    0.   11.09] Na ...
793 clusters will be generated ...

Generating possible clusters within this diffusion unit...
Cutoffs: pair = 6 Angst, triplet = 6 Angst, quadruplet = 0 Angst
Type	Index	max_length	min_length	Point Group	Multiplicity
point	(0,)      	   0.000	   0.000	Kh   	    6
point	(6,)      	   0.000	   0.000	Kh   	    6
pair 	(0, 1)    	   4.727	   4.727	D*h  	    6
pair 	(0, 3)    	   5.103	   5.103	D*h  	    6
pair 	(0, 6)    	   3.710	   3.710	C*v  	    6
pair 	(0, 7)    	   3.056	   3.056	C*v  	    6
pair 	(0, 8)    	   3.162	   3.162	C*v  	    6
pair 	(6, 7)    	   4.922	   4.922	D*h  	    6
pair 	(6, 9)    	   5.629	   5.629	D*h  	    6
triplet	(0, 1, 2) 	   5.103	   4.727	C2v  	    6
triplet	(0, 1, 6) 	   4.727	   3.162	Cs   	    6
triplet	(0, 1, 7) 	   4.727	   3.056	Cs   	    6
triplet	(0, 3, 4) 	   5.103	   5.103	D3h  	    2
triplet	(0, 3, 7) 	   5.103	   3.056	C2v  	    6
triplet	(0, 6, 7) 	   4.922	   3.056	Cs   	    6
triplet	(0,

the kmc.event_generator is for generating the **event_kernal.csv and events.json**

read the primitive cell from prim.json, and write events.json as output

In [ ]:
from kmcpy.event_generator import generate_events

generate_events(prim_fname=r"../examples/inputs/prim.json",supercell_shape=[2,1,1],event_fname="./events.json",event_kernal_fname='./event_kernal.csv')

Following block run the kmc version 1

In [1]:


from kmcpy.io import InputSet,load_occ
from kmcpy.kmc import KMC
import os
import sys

def main(api=1,**kwargs):
    os.chdir("./1stinput")
    

    
    
    
    inputset=InputSet.from_json("./test_input.json")

    print(inputset._parameters.keys())
    inputset.parameter_checker()

    if api==1:


        inputset.set_parameter("occ",load_occ(inputset._parameters["mc_results"],inputset._parameters["supercell_shape"],api=inputset.api))
        # step 1 initialize global occupation and conditions
        kmc = KMC()
        events_initialized = kmc.initialization(**inputset._parameters) # v in 10^13 hz

        # # step 2 compute the site kernal (used for kmc run)
        kmc.load_site_event_list(inputset._parameters["event_kernel"])

        # # step 3 run kmc
        kmc.run_from_database(events=events_initialized,**inputset._parameters)
    if api>1:
        raise NotImplementedError
    pass


if __name__ == "__main__":

    main()


dict_keys(['v', 'equ_pass', 'kmc_pass', 'supercell_shape', 'fitting_results', 'fitting_results_site', 'lce_fname', 'lce_site_fname', 'prim_fname', 'event_fname', 'event_kernel', 'mc_results', 'T', 'comp', 'structure_idx', 'api'])
Initializing kMC calculations with pirm.json at ./inputs/prim.json ...
Supercell Shape:
 [[2 0 0]
 [0 1 0]
 [0 0 1]]
Converting supercell ...
Loading fitting results ...
Loading fitting results (site energy) ...
Loading occupation: [-1 -1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1  1 -1 -1  1 -1 -1 -1
 -1 -1 -1 -1]
Fitted time and error (LOOCV,RMS)
01/21/2022, 16:49:17 149.8671381416 29.1495050791
Fitted KECI and empty cluster
[10.5029085379, 4.0803809727, 0.0, 0.0, -11.2639080302, 0.0, -4.0578126572, 0.0, -7.2124075988, 0.0, 0.0, 0.0, 0.0] 339.1083600548
Fitted time and error (LOOCV,RMS) (site energy)
01/21/2022, 16:49:17 149.8671381416 29.1495050791
Fitted KECI and empty cluster (site energy)
[10.5029085379, 4.0803809727, 0.0, 0.0, -11.2639080302, 0.0, -4.

/Users/weihangxie/Documents/GitHub/kmcPy/kmcpy/tracker.py:93: RuntimeWarning: invalid value encountered in true_divide
  corr_factor = np.linalg.norm(self.displacement,axis=1)**2/(self.hop_counter*a**2)


42	8.771E-06	9.552E+01	3.598E-10	1.815E-10	2.908E-02	5.044E-01	1.930E-01	0.29	0.24
43	9.036E-06	1.051E+02	4.601E-10	1.938E-10	3.718E-02	4.212E-01	1.946E-01	0.29	0.24
44	1.058E-05	1.203E+02	5.281E-10	1.894E-10	4.268E-02	3.586E-01	2.165E-01	0.29	0.24
45	1.063E-05	1.328E+02	6.166E-10	2.081E-10	4.983E-02	3.376E-01	2.560E-01	0.29	0.24
46	1.088E-05	1.322E+02	6.728E-10	2.025E-10	5.437E-02	3.010E-01	2.377E-01	0.29	0.24
47	1.096E-05	1.357E+02	6.685E-10	2.064E-10	5.402E-02	3.087E-01	2.371E-01	0.29	0.24
48	1.120E-05	1.253E+02	7.045E-10	1.864E-10	5.693E-02	2.646E-01	2.244E-01	0.29	0.24
49	1.126E-05	1.549E+02	9.574E-10	2.292E-10	7.737E-02	2.394E-01	2.645E-01	0.29	0.24
50	1.146E-05	1.452E+02	8.586E-10	2.111E-10	6.939E-02	2.458E-01	2.188E-01	0.29	0.24
51	1.156E-05	1.404E+02	7.738E-10	2.023E-10	6.254E-02	2.615E-01	2.168E-01	0.29	0.24
52	1.166E-05	1.564E+02	9.073E-10	2.236E-10	7.333E-02	2.464E-01	2.415E-01	0.29	0.24
53	1.170E-05	1.733E+02	1.068E-09	2.468E-10	8.632E-02	2.311E-01	2.667E-01	0.29	0.24
54	1

Api version 2 initiated
aiming for more flexible inputs.
Following block is the main KMC function
DO make sure that they provide similar result as in API=1
KMC result is not necessarily the same, since it is randomized

In [ ]:
#!/usr/bin/env python

from kmcpy.io import InputSet,load_occ
from kmcpy.kmc import KMC
import os
import sys

def main(api=2,**kwargs):
    inputset=InputSet.from_json("test_input_v2.json",api=2)

    print(inputset._parameters.keys())
    inputset.parameter_checker()

    inputset.set_parameter("occ",load_occ(fname=inputset._parameters["mc_results"],shape=inputset._parameters["supercell_shape"],select_sites=inputset._parameters["select_sites"],api=inputset.api,verbose=True))
    
    
    

    # step 1 initialize global occupation and conditions
    
    
    
    kmc = KMC(api=api)
    events_initialized = kmc.initialization(**inputset._parameters) # v in 10^13 hz

    # # step 2 compute the site kernal (used for kmc run)
    kmc.load_site_event_list(inputset._parameters["event_kernel"])

    # # step 3 run kmc
    kmc.run_from_database(events=events_initialized,**inputset._parameters)


if __name__ == "__main__":

    main()

testing the sites_and_lattices.py

我写的site lattice太智障了,看不懂.


根据piero建议,还是用structure写吧.....

In [ ]:
from kmcpy.external.pymatgen_structure import Structure
from pymatgen.symmetry.analyzer  import SpacegroupAnalyzer
from kmcpy.external.pymatgen_local_env import CutOffDictNN
structure=Structure.from_cif("/Users/weihangxie/Documents/GitHub/kmcPy/dev_test/EntryWithCollCode15546_Na4Zr2Si3O12_573K.cif")



#print(structure.site_properties)
print(structure)

#print(structure[5].properties)

structure.make_supercell(scaling_matrix=[1,1,2])
#print(structure.site_properties)
local_env_cutoff_dict = {('Na+','Na+'):4,('Na+','Si4+'):4}
local_env_finder = CutOffDictNN(local_env_cutoff_dict)
local_env_finder.get_nn_info(structure,0)   
from kmcpy.model import LocalClusterExpansion



a=LocalClusterExpansion(api=1)
a.initialization(center_Na1_index=0,cutoff_cluster=[6,6,6],cutoff_region=4,template_cif_fname='./EntryWithCollCode15546_Na4Zr2Si3O12_573K.cif')
a=LocalClusterExpansion(api=2)
a.initialization(center_atom_index=0,cutoff_cluster=[6,6,6],cutoff_region=4,template_cif_fname='./EntryWithCollCode15546_Na4Zr2Si3O12_573K.cif')
a.to_json("test_LCEv2.json")


test on find_site_by_wyckoff_sequence_and_label

test on nd supercell

test the new event generator

Problem!!!!! LOok the distance matrix, they are not all the same

Fixed now

In [1]:
from kmcpy.event_generator import generate_events2
from kmcpy.external.pymatgen_structure import Structure

primitive_structure=Structure.from_file("EntryWithCollCode15546_Na4Zr2Si3O12_573K.cif",primitive=True)
primitive_structure.to("cif","primitive_EntryWithCollCode15546_Na4Zr2Si3O12_573K.cif")


#generate_events2(prim_cif_name="primitive_EntryWithCollCode15546_Na4Zr2Si3O12_573K.cif",supercell_shape=[2,3,4],local_env_cutoff_dict = {('Na+','Na+'):4,('Na+','Si4+'):4},event_fname="events.json",event_kernal_fname='event_kernal.csv',center_atom_label_or_indices="Na1",species_to_be_removed=['Zr4+','O2-','O','Zr'],verbose=True)


#generate_events2(prim_cif_name="EntryWithCollCode15546_Na4Zr2Si3O12_573K.cif",supercell_shape=[2,3,4],local_env_cutoff_dict = {('Na+','Na+'):4,('Na+','Si4+'):4},event_fname="events.json",event_kernal_fname='event_kernal.csv',center_atom_label_or_indices="Na1",species_to_be_removed=['Zr4+','O2-','O','Zr'],verbose=True,hacking_arg={1: [27, 29, 28, 30, 32, 31, 117, 119, 118, 120, 122, 121],2:[21,22,23,32,30,31,111,112,113,122,120,121],3:[18,20,19,34,33,35,108,110,109,124,123,125],5:[21,23,22,24,26,25,111,113,112,114,116,115]})
#generate_events2(prim_cif_name="EntryWithCollCode15546_Na4Zr2Si3O12_573K.cif",supercell_shape=[2,1,1],local_env_cutoff_dict = {('Na+','Na+'):4,('Na+','Si4+'):4},event_fname="events.json",event_kernal_fname='event_kernal.csv',center_atom_label_or_indices="Na1",species_to_be_removed=['Zr4+','O2-','O','Zr'],verbose=True,hacking_arg={2:[21,22,23,32,30,31,111,112,113,122,120,121],3:[18,20,19,34,33,35,108,110,109,124,123,125],5:[21,23,22,24,26,25,111,113,112,114,116,115]})

generate_events2(prim_cif_name="EntryWithCollCode15546_Na4Zr2Si3O12_573K.cif",supercell_shape=[2,1,1],local_env_cutoff_dict = {('Na+','Na+'):4,('Na+','Si4+'):4},event_fname="events.json",event_kernal_fname='event_kernal.csv',center_atom_label_or_indices="Na1",species_to_be_removed=['Zr4+','O2-','O','Zr'],verbose=True,hacking_arg=None)


{(0.0, 0.0, 0.14719): Comp: Zr1, (0.0, 0.0, 0.0): Comp: Na1, (-0.36033, 0.0, 0.25): Comp: Na1, (0.18534, 0.16651, 0.08652): Comp: O1, (0.18214, 0.02102, 0.19199): Comp: O1, (0.29544, 0.0, 0.25): Comp: Si1}
Generating events ...
Initializing model with input cif file at EntryWithCollCode15546_Na4Zr2Si3O12_573K.cif ...
{(0.0, 0.0, 0.14719): Comp: Zr1, (0.0, 0.0, 0.0): Comp: Na1, (-0.36033, 0.0, 0.25): Comp: Na1, (0.18534, 0.16651, 0.08652): Comp: O1, (0.18214, 0.02102, 0.19199): Comp: O1, (0.29544, 0.0, 0.25): Comp: Si1}


-------------------------------------------


primitive cell: Full Formula (Na8 Si6)
Reduced Formula: Na4Si3
abc   :   9.099213   9.099213   9.099213
angles:  60.634218  60.634218  60.634218
Sites (14)
  #  SP          a        b        c  label      local_index    wyckoff_sequence
---  ----  -------  -------  -------  -------  -------------  ------------------
  0  Na+   0.5      0.5      0.5      Na1                 12                   0
  1  Na+   0        0       

完整的第二版测试?

注意,prim.json读进structure之后,再输出成cif,注意输出cif时候要给过去一个symprec变量.这样生成出来的cif是有对称性的.然后要参照cif里面的Label更改center atom 和 diffuse to atom. 这里面分别是Na1 和Na0

所有输入文件在2ndinput文件夹里面

目前问题是,读不进去fittingresult.json

强行加了几行让他能运行


如果不加这几行的话

ValueError: shapes (22,) and (13,) not aligned: 22 (dim 0) != 13 (dim 0)

13是fittingresult里面keci的长度

22是local cluster expansion 里面的cluster总数

好像原因是这个local cluster expansion得到的不一样?


In [4]:
from kmcpy.event_generator import generate_events2

convert_to_primitive_cell=True
# event kernal
generate_events2(prim_cif_name="EntryWithCollCode15546_Na4Zr2Si3O12_573K.cif",convert_to_primitive_cell=convert_to_primitive_cell,supercell_shape=[2,1,1],local_env_cutoff_dict = {('Na+','Na+'):4,('Na+','Si4+'):4},event_fname="2ndinput/events.json",event_kernal_fname='2ndinput/event_kernal.csv',center_atom_label_or_indices="Na1",species_to_be_removed=['Zr4+','O2-','O','Zr'],diffuse_to_atom_label="Na2",verbose=True,hacking_arg={1: [18, 20, 19, 22, 21, 23, 108, 110, 109, 112, 111, 113]})

# model kernal

from kmcpy.model import LocalClusterExpansion

a=LocalClusterExpansion(api=2)
a.initialization(center_atom_index="Na1",cutoff_cluster=[6,6,0],cutoff_region=4,template_cif_fname='./EntryWithCollCode15546_Na4Zr2Si3O12_573K.cif',species_to_be_removed=['Zr4+','O2-','O','Zr'],convert_to_primitive_cell=convert_to_primitive_cell)
a.to_json("2ndinput/lce.json")
a.to_json("2ndinput/lce_site.json")

from kmcpy.io import InputSet,load_occ
from kmcpy.kmc import KMC


def main(api=2,**kwargs):
    inputset=InputSet.from_json("2ndinput/test_input_v2.json",api=2)

    print(inputset._parameters.keys())
    print(inputset._parameters["mc_results"])
    inputset.parameter_checker()

    inputset.set_parameter("occ",load_occ(fname=inputset._parameters["mc_results"],shape=inputset._parameters["supercell_shape"],select_sites=inputset._parameters["select_sites"],api=inputset.api,verbose=True))
    
    
    

    # step 1 initialize global occupation and conditions
    
    
    
    kmc = KMC(api=api)
    events_initialized = kmc.initialization(**inputset._parameters) # v in 10^13 hz

    # # step 2 compute the site kernal (used for kmc run)
    kmc.load_site_event_list(inputset._parameters["event_kernel"])

    # # step 3 run kmc
    kmc.run_from_database(events=events_initialized,**inputset._parameters)


if __name__ == "__main__":

    main()




Generating events ...
Initializing model with input cif file at EntryWithCollCode15546_Na4Zr2Si3O12_573K.cif ...
{(0.0, 0.0, 0.14719): Comp: Zr1, (0.0, 0.0, 0.0): Comp: Na1, (-0.36033, 0.0, 0.25): Comp: Na1, (0.18534, 0.16651, 0.08652): Comp: O1, (0.18214, 0.02102, 0.19199): Comp: O1, (0.29544, 0.0, 0.25): Comp: Si1}


-------------------------------------------


primitive cell: Full Formula (Na8 Si6)
Reduced Formula: Na4Si3
abc   :   9.099213   9.099213   9.099213
angles:  60.634218  60.634218  60.634218
Sites (14)
  #  SP          a        b        c  label      local_index    wyckoff_sequence
---  ----  -------  -------  -------  -------  -------------  ------------------
  0  Na+   0.5      0.5      0.5      Na1                 12                   0
  1  Na+   0        0        0        Na1                 13                   1
  2  Na+   0.88967  0.61033  0.25     Na2                 18                   0
  3  Na+   0.61033  0.25     0.88967  Na2                 19            

ValueError: shapes (19,) and (13,) not aligned: 19 (dim 0) != 13 (dim 0)

In [3]:
print([10]+[6,6,6])


[10, 6, 6, 6]
