这个notebook是在写代码时候用来测试比如,nparray和list区别之类的,不是用来测试代码里面的函数的.

matrix multiplication

In [ ]:
import numpy as np

# a 4*1 matrix
d4coordinate=np.array([1,2,3,1]).reshape(4,1)

# a symmetry operator
symmetry_matrix=np.array([[ 1.        ,  0.        ,  0.        ,  0.66666667],
       [ 1.        , -1.        ,  0.        ,  0.33333333],
       [ 0.        ,  0.        ,  1.        ,  0.83333333],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

# do the multiplication. results in a 4*1 matrix
np.matmul(symmetry_matrix,d4coordinate)

# revert to 1*3

#np.matmul(symmetry_matrix,d4coordinate).reshape(1,4).tolist()[0][0:3]

判断is new site,或者说,输入一个array和array list,看这个array在不在另外一个array list里面(或者说重复)

In [ ]:
array_list=[np.array([[ 1.66666667],
       [-0.66666667],
       [ 3.83333333],
       [ 1.        ]]),np.array([[ 2.66666667],
       [-0.66666697],
       [ 3.83333323],
       [ 1.        ]]),np.array([[ 1.66666667],
       [-0.67666667],
       [ 3.83333333],
       [ 1.        ]])]

to_be_compared=np.array([[ 1.66666667],
       [-0.66666667],
       [ 3.83333333],
       [ 1.        ]])

print(array_list-to_be_compared)
print("sum axis0:",np.sum(array_list-to_be_compared,axis=0))
print("sum axis1:",np.sum(array_list-to_be_compared,axis=1))
print("sum axis2:",np.sum(array_list-to_be_compared,axis=2))
print(" sum of axis 1 is correct.")
print("sum of abs of axis1:",np.sum(np.abs(array_list-to_be_compared),axis=1))
tolerence=0.01
print("determine abs:",np.sum(np.abs(array_list-to_be_compared),axis=1)<tolerence)
print("test any:",np.any(np.sum(np.abs(array_list-to_be_compared),axis=1)<tolerence))
print("not test any:", not(np.any(np.sum(np.abs(array_list-to_be_compared),axis=1)<tolerence)))

testing hash

In [12]:
print([1,2].__hash__)
print((1).__hash__())
print((2).__hash__())
print("Na1".__hash__())
print(tuple([1,2]).__hash__())
print((1,2).__hash__())
print(str(tuple([1,2])).__hash__())

None
1
2
-8427478013190458469
-3550055125485641917
-3550055125485641917
7192916101901552022


this is a block for generating all symmetry operations of R-3m

In [1]:
from pymatgen.symmetry.analyzer  import SpacegroupAnalyzer
from kmcpy.external.pymatgen_structure import Structure
nzsp=Structure.from_file("EntryWithCollCode15546_Na4Zr2Si3O12_573K.cif")
a=SpacegroupAnalyzer(nzsp)
#print(a.get_conventional_to_primitive_transformation_matrix())
#print(a.get_space_group_operations())
#print(a.get_symmetry_dataset())
for i in a.get_symmetry_operations():
    print(i.affine_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[-1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0.  1.]]
[[ 0. -1.  0.  0.]
 [ 1. -1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 0.  1.  0.  0.]
 [-1.  1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0.  1.]]
[[-1.  1.  0.  0.]
 [-1.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 1. -1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0.  1.]]
[[ 0.          1.          0.          0.33333333]
 [ 1.          0.          0.          0.66666667]
 [ 0.          0.         -1.          0.16666667]
 [ 0.          0.          0.          1.        ]]
[[ 0.         -1.          0.          0.33333333]
 [-1.          0.          0.          0.66666667]
 [ 0.          0.          1.          0.16666667]
 [ 0.          0.          0.          1.        ]]
[[ 1.         -1.          0.          0.33333333]
 [ 0.         -1.          0.          0.66666667]
 [ 0.          0.         -1.          0.1