# Test on $LiCoO_2$

First We will have to add a dummy atom in the center of 3-Li-triangle, as the center of cluster expansion

In [1]:
from kmcpy.external.pymatgen_structure import Structure
LiCoO2=Structure.from_cif("EntryWithCollCode51182.cif")
LiCoO2.make_supercell([2,2,1])
import numpy as np
#np.set_printoptions(precision=2)
for site in LiCoO2:
    if "Li+" in site:
        print(site,site.properties,site.frac_coords)
print(LiCoO2)


[0. 0. 0.] Li+ {'wyckoff_sequence': 0, 'local_index': 0, 'label': 'Li1'} [0. 0. 0.]
[-1.40805000e+00  2.43881414e+00  1.72436393e-16] Li+ {'wyckoff_sequence': 0, 'local_index': 0, 'label': 'Li1'} [0.  0.5 0. ]
[2.81610000e+00 0.00000000e+00 1.72436393e-16] Li+ {'wyckoff_sequence': 0, 'local_index': 0, 'label': 'Li1'} [0.5 0.  0. ]
[1.40805000e+00 2.43881414e+00 3.44872785e-16] Li+ {'wyckoff_sequence': 0, 'local_index': 0, 'label': 'Li1'} [0.5 0.5 0. ]
[1.40805    0.81293805 4.68453333] Li+ {'wyckoff_sequence': 1, 'local_index': 1, 'label': 'Li1'} [0.33333333 0.16666667 0.33333333]
[-1.17827970e-16  3.25175219e+00  4.68453333e+00] Li+ {'wyckoff_sequence': 1, 'local_index': 1, 'label': 'Li1'} [0.33333333 0.66666667 0.33333333]
[4.22415    0.81293805 4.68453333] Li+ {'wyckoff_sequence': 1, 'local_index': 1, 'label': 'Li1'} [0.83333333 0.16666667 0.33333333]
[2.8161     3.25175219 4.68453333] Li+ {'wyckoff_sequence': 1, 'local_index': 1, 'label': 'Li1'} [0.83333333 0.66666667 0.33333333]
[

Here the 1st, 3rd, 4th Li+ obviously form a triangle, refer to Anton's paper (Van Der Ven A, Ceder G. Lithium diffusion in layered LixCoO2 Electrochemical and Solid-State Letters. 3: 301-304. DOI: 10.1149/1.1391130), the center of local cluster expansion is the center of such Lithium triangle. Then we need to add an dummy atom in the center for events generator

In [2]:
from kmcpy.external.pymatgen_structure import Structure
import numpy

def add_dummy(structure1,structure2,site1,site2,site3):
    structure1.append(species="Na+",coords=(structure2[site1].coords+structure2[site2].coords+structure2[site3].coords)/3,coords_are_cartesian=True,properties={'local_index':0, 'label': 'dummy'})

LiCoO2_2=Structure.from_cif("EntryWithCollCode51182.cif")

for center_Li in [[0,2,3],[0,1,3],[4,6,7],[4,5,7],[8,10,11],[8,9,11]]:
    add_dummy(LiCoO2_2,LiCoO2,*center_Li)

print(LiCoO2_2)
LiCoO2_2.to("cif","LiCoO2_dummy_added.cif",symprec=0.01)

Full Formula (Na6 Li3 Co3 O6)
Reduced Formula: Na2LiCoO2
abc   :   2.816100   2.816100  14.053600
angles:  90.000000  90.000000 120.000000
Sites (18)
  #  SP           a         b         c  label      local_index    wyckoff_sequence
---  ----  --------  --------  --------  -------  -------------  ------------------
  0  Li+   0         0         0         Li1                  0                   0
  1  Li+   0.666667  0.333333  0.333333  Li1                  1                   1
  2  Li+   0.333333  0.666667  0.666667  Li1                  2                   2
  3  Co3+  0         0         0.5       Co1                  3                   0
  4  Co3+  0.666667  0.333333  0.833333  Co1                  4                   1
  5  Co3+  0.333333  0.666667  0.166667  Co1                  5                   2
  6  O2-   0         0         0.76049   O1                   6                   0
  7  O2-   0         0         0.23951   O1                   7                   1
  8  O2-  

In [3]:
mobile_ion_identifier_type="label"
mobile_ion_specie_1_identifier="Na0"
mobile_ion_specie_2_identifier="Li1"
prim_cif_name="LiCoO2_dummy_added.cif"
local_env_cutoff_dict={('Na+','Li+'):4.31}
from kmcpy.event_generator import generate_events3
generate_events3(prim_cif_name=prim_cif_name,local_env_cutoff_dict=local_env_cutoff_dict,mobile_ion_identifier_type=mobile_ion_identifier_type,mobile_ion_specie_1_identifier=mobile_ion_specie_1_identifier,mobile_ion_specie_2_identifier=mobile_ion_specie_2_identifier,species_to_be_removed=["O2-","O","Co+","Co"],distance_matrix_rtol=0.01,distance_matrix_atol=0.01,find_nearest_if_fail=False,convert_to_primitive_cell=False,export_local_env_structure=True,supercell_shape=[2,2,2],event_fname="events.json",event_kernal_fname='event_kernal.csv',verbosity="INFO")

Extracting clusters from primitive cell structure. This primitive cell should be bulk structure, grain boundary model not implemented yet.
/Users/weihangxie/Documents/GitHub/kmcPy_dev/kmcpy/external/pymatgen_cif.py:1498: UserWarning: Issues encountered while parsing CIF: Some fractional coordinates rounded to ideal values to avoid issues with finite precision.
  warnings.warn("Issues encountered while parsing CIF: %s" % "\n".join(self.warnings))
primitive cell composition after adding oxidation state and removing uninvolved species: 
Na+6 Li+3
building mobile_ion_specie_1 index list
please check if these are mobile_ion_specie_1:
[0.         0.         4.68453333] Na+
[0.         0.         9.36906667] Na+
[1.40805    0.81293805 9.36906667] Na+
[1.40805000e+00 8.12938047e-01 1.72436393e-16] Na+
[1.63130620e-16 1.62587609e+00 1.72436393e-16] Na+
[1.63130620e-16 1.62587609e+00 4.68453333e+00] Na+
start finding the neighboring sequence of mobile_ion_specie_1s
total number of mobile_ion_spe

KeyboardInterrupt: 

In [1]:
mobile_ion_identifier_type="label"
mobile_ion_specie_1_identifier="Na0"
mobile_ion_specie_2_identifier="Li1"
prim_cif_name="LiCoO2_dummy_added.cif"
local_env_cutoff_dict={('Na+','Li+'):4.31}
from kmcpy.event_generator import *
import itertools
class neighbor_info_matcher():
    def __init__(self,neighbor_species=(('Cl-', 4),('Li+', 8)),distance_matrix=np.array([[0,1],[1,0]]),neighbor_sequence=[{}],neighbor_species_distance_matrix_dict={"Cl-":np.array([[0,1],[1,0]]),"Li+":np.array([[0,1],[1,0]])},neighbor_species_sequence_dict={"Cl-":[{}],"Li+":[{}]}):
        """neighbor_info matcher, the __init__ method shouln't be used. Use the from_neighbor_info() instead. This is neighbor_info matcher to match the nearest neighbor info output from local_env.cutoffdictNN.get_nn_info. This neighbor_info_matcher Class is initialized by a reference neighbor_info, a distance matrix is built as reference. Then user can call the neighbor_info_matcher.brutal_match function to sort another nn_info so that the sequence of neighbor of "another nn_info" is arranged so that the distance matrix are the same 

        Args:
            neighbor_species (tuple, optional): tuple ( tuple ( str(species), int(number_of_this_specie in neighbors)  )  ). Defaults to (('Cl-', 4),('Li+', 8)).
            distance_matrix (np.array, optional): np.2d array as distance matrix. Defaults to np.array([[0,1],[1,0]]).
            neighbor_sequence (list, optional): list of dictionary in the format of nn_info returning value. Defaults to [{}].
            neighbor_species_distance_matrix_dict (dict, optional): this is a dictionary with key=species and value=distance_matrix(2D numpy array) which record the distance matrix of respective element. . Defaults to {"Cl-":np.array([[0,1],[1,0]]),"Li+":np.array([[0,1],[1,0]])}.
            neighbor_species_sequence_dict (dict, optional): dictionary with key=species and value=list of dictionary which is just group the reference neighbor sequence by different elements. Defaults to {"Cl-":[{}],"Li+":[{}]}.
        """
        
        self.neighbor_species=neighbor_species
        self.distance_matrix=distance_matrix
        self.neighbor_species_distance_matrix_dict=neighbor_species_distance_matrix_dict
        self.neighbor_species_sequence_dict=neighbor_species_sequence_dict
        self.neighbor_sequence=neighbor_sequence
    
    @classmethod
    def from_neighbor_sequences(self,neighbor_sequences=[{}]):
        """generally generate the neighbor info matcher from this

        Args:
            neighbor_sequences (list, optional): list of dictionary from cutoffdictNN.get_nn_info(). Defaults to [{}].

        Returns:
            neighbor_info_matcher: a neighbor_info_matcher object, initialized from get_nn_info output
        """
        
        # -------------------------------------------------------
        # this part of function is adapted from pymatgen.analysis.local_env
        #Shyue Ping Ong, William Davidson Richards, Anubhav Jain, Geoffroy Hautier, Michael Kocher, Shreyas Cholia, Dan Gunter, Vincent Chevrier, Kristin A. Persson, Gerbrand Ceder. Python Materials Genomics (pymatgen) : A Robust, Open-Source Python Library for Materials Analysis. Computational Materials Science, 2013, 68, 314-319. doi:10.1016/j.commatsci.2012.10.028
        cn_dict={}
        
        neighbor_species_sequence_dict={}
        
        for neighbor in neighbor_sequences:
            """for example NaSICON has 12 neighbors, 6 Na and 6 Si, here for neighbor we build the coordination number dict.
            """
            
            site_element = neighbor["site"].species_string
            
            if site_element not in cn_dict:
                cn_dict[site_element] = 1
            else:
                cn_dict[site_element] += 1
            if site_element not in neighbor_species_sequence_dict:
                neighbor_species_sequence_dict[site_element]=[neighbor]
            else:
                neighbor_species_sequence_dict[site_element].append(neighbor)
        # end of adapting.
        # -------------------------------------------------------        
            
        neighbor_species_distance_matrix_dict={}
        
        for species in neighbor_species_sequence_dict:
            neighbor_species_distance_matrix_dict[species]=self.build_distance_matrix_from_getnninfo_output(neighbor_species_sequence_dict[species])
        
        neighbor_species=tuple(sorted(cn_dict.items(),key=lambda x:x[0]))
        
        distance_matrix=self.build_distance_matrix_from_getnninfo_output(neighbor_sequences)
        
        
         
        return neighbor_info_matcher(neighbor_species=neighbor_species,distance_matrix=distance_matrix,neighbor_sequence=neighbor_sequences,neighbor_species_distance_matrix_dict=neighbor_species_distance_matrix_dict,neighbor_species_sequence_dict=neighbor_species_sequence_dict)
        
    
    @classmethod
    def build_distance_matrix_from_getnninfo_output(self,cutoffdnn_output=[{}]):
        """build a distance matrix from the output of CutOffDictNN.get_nn_info

        nn_info looks like: 
        [{'site': PeriodicSite: Si4+ (-3.2361, -0.3015, 9.2421) [-0.3712, -0.0379, 0.4167], 'image': (-1, -1, 0), 'weight': 3.7390091507903174, 'site_index': 39, 'wyckoff_sequence': 15, 'local_index': 123, 'label': 'Si1'}, {'site': PeriodicSite: Na+ (-1.2831, -2.6519, 9.2421) [-0.3063, -0.3333, 0.4167], 'image': (-1, -1, 0), 'weight': 3.4778161424304046, 'site_index': 23, 'wyckoff_sequence': 17, 'local_index': 35, 'label': 'Na2'}, {'site': ...]
        
        or say:
        
        nn_info is a list, the elements of list is dictionary, the keys of dictionary are: "site":pymatgen.site, "wyckoff_sequence": ....
        
        Use the site.distance function to build matrix
        

        Args:
            cutoffdnn_output (nn_info, optional): nninfo. Defaults to neighbor_sequences.

        Returns:
            np.2darray: 2d distance matrix, in format of numpy.array. The Column and the Rows are following the input sequence.
        """
    
        distance_matrix=np.zeros(shape=(len(cutoffdnn_output),len(cutoffdnn_output)))
          

        for sitedictindex1 in range(0,len(cutoffdnn_output)):
            for sitedictindex2 in range(0,sitedictindex1):
                """Reason for jimage=[0,0,0]
                
                site.distance is calculated by frac_coord1-frac_coord0 and get the cartesian distance. Note that for the two sites in neighbors,  the frac_coord itself already contains the information of jimage. For exaple:Si4+ (-3.2361, -0.3015, 9.2421) [-0.3712, -0.0379, 0.4167], 'image': (-1, -1, 0),  see that the frac_coord of this Si4+ is not normalized to (0,1)!

                .
                """
                distance_matrix[sitedictindex1][sitedictindex2]=cutoffdnn_output[sitedictindex1]["site"].distance(cutoffdnn_output[sitedictindex2]["site"],jimage=[0,0,0])
            
            
        
        return distance_matrix

    @classmethod
    def build_angle_matrix_from_getnninfo_output(self,cutoffdnn_output=[{}]):
        """build a distance matrix from the output of CutOffDictNN.get_nn_info

        nn_info looks like: 
        [{'site': PeriodicSite: Si4+ (-3.2361, -0.3015, 9.2421) [-0.3712, -0.0379, 0.4167], 'image': (-1, -1, 0), 'weight': 3.7390091507903174, 'site_index': 39, 'wyckoff_sequence': 15, 'local_index': 123, 'label': 'Si1'}, {'site': PeriodicSite: Na+ (-1.2831, -2.6519, 9.2421) [-0.3063, -0.3333, 0.4167], 'image': (-1, -1, 0), 'weight': 3.4778161424304046, 'site_index': 23, 'wyckoff_sequence': 17, 'local_index': 35, 'label': 'Na2'}, {'site': ...]
        
        or say:
        
        nn_info is a list, the elements of list is dictionary, the keys of dictionary are: "site":pymatgen.site, "wyckoff_sequence": ....
        
        Use the site.distance function to build matrix
        

        Args:
            cutoffdnn_output (nn_info, optional): nninfo. Defaults to neighbor_sequences.

        Returns:
            np.3darray: 3d distance matrix, in format of numpy.array. The Column and the Rows are following the input sequence.
        """
    
        angle_matrix=np.zeros(shape=(len(cutoffdnn_output),len(cutoffdnn_output),len(cutoffdnn_output)))
          
        
        for sitedictindex1 in range(0,len(cutoffdnn_output)):
            for sitedictindex2 in range(0,sitedictindex1):
                for sitedictindex3 in range(0,sitedictindex2):
                    v1=cutoffdnn_output[sitedictindex2]["site"].coords-cutoffdnn_output[sitedictindex1]["site"].coords
                    v2=cutoffdnn_output[sitedictindex3]["site"].coords-cutoffdnn_output[sitedictindex1]["site"].coords
                    angle_matrix[sitedictindex1][sitedictindex2][sitedictindex3]=get_angle(v1,v2,"degrees")
            
            
        
        return angle_matrix

    def rearrange(self,distance_matrix=[],species='Na'):
        # distance_matrix=distance matrix of wrong neighbor sequence
        correct_distance_matrix=self.neighbor_species_distance_matrix_dict[species]# np.2darray
        previous_possible_sequences=[]
        for i in range(0,len(correct_distance_matrix)):
            previous_possible_sequences.append([i])
        
        for i in range(0,len(correct_distance_matrix)):
        
            new_possible_sequences=[]
            
            correct_distance_matrix_in_this_round=correct_distance_matrix[0:2+i,0:2+i]
            
            
            for previous_possible_sequence in previous_possible_sequences:
                for i in range(0,len(correct_distance_matrix)):
                    if i not in previous_possible_sequence:
                        tmp_sequence=previous_possible_sequence.copy()
                        tmp_sequence.extend(i)
                        tmp_rebuilt_submatrix=self.rebuild_submatrix(correct_distance_matrix=correct_distance_matrix,sequences=tmp_sequence)
                        if np.allclose(tmp_rebuilt_submatrix,correct_distance_matrix_in_this_round):
                            new_possible_sequences.append(tmp_rebuilt_submatrix)
                            
            previous_possible_sequences=new_possible_sequences
            
        if len(new_possible_sequences)==0:
            raise ValueError("new possible sequence=0.")
        else:
            return new_possible_sequences[0]
            


    def rebuild_submatrix(self,correct_distance_matrix,sequences=[2,1]):
        # correct_distance_matrix=self.neighbor_species_distance_matrix_dict[species]
        rebuilt_matrix=np.zeros(shape=(len(sequences),len(sequences)))
        
        for idx1 in range(sequences):
            for idx2 in range(sequences):
                rebuilt_matrix[idx1][idx2]=correct_distance_matrix[sequences[idx1]][sequences[idx2]]
        return rebuilt_matrix


    def brutal_match(self,unsorted_nninfo=[{}],rtol=0.001,atol=0.001,find_nearest_if_fail=False):
        """brutally sort the input unsorted_nninfo. Although brutal but fast enough for now

        Args:
            unsorted_nninfo (list, optional): the unsorted nn_info of an element. The nn_info are compared with the nn_info of class instance. Defaults to [{}].
            
            Tolerance: Refer to np.allclose
            rtol (float, optional): relative tolerance of np.allclose in order to determine if the distance matrix are the same. Better not too small. Defaults to 0.01.
            atol (float, optional): absolute tolerance
            find_nearest_if_fail(bool, optional): This should be true only for grain boundary model! 

        Raises:
            ValueError: this will perform a check if the inputted unsorted nn_info has the same neighbor species type and amount
            ValueError: if the unsorted_nninfo cannot be sort with reference of the distance matrix of this neighbor_info_matcher instance. Probably due to too small rtol or it's just not the same neighbor_infos

        Returns:
            sorted nninfo, as list of dictionary: in the format of cutoffdictNN.get_nn_info
        """
        
        unsorted_neighbor_info=neighbor_info_matcher.from_neighbor_sequences(unsorted_nninfo)
        
        if self.neighbor_species!=unsorted_neighbor_info.neighbor_species:
            raise ValueError("input neighbor_info has different environment")
        
        if np.allclose(unsorted_neighbor_info.distance_matrix,self.distance_matrix,rtol=rtol,atol=atol):
            neighbor_info_logger.info("no need to rearrange this neighbor_info. The distance matrix is already the same. The differece matrix is : \n")
            neighbor_info_logger.info(str(unsorted_neighbor_info.distance_matrix-self.distance_matrix))
            
            return unsorted_neighbor_info.neighbor_sequence
        
        
        
        sorted_neighbor_sequence_dict={}

        for specie in unsorted_neighbor_info.neighbor_species_sequence_dict:
            
            sorted_neighbor_sequence_dict[specie]=self.rearrange(unsorted_neighbor_info.neighbor_species_distance_matrix_dict[specie],species=specie)

            print(sorted_neighbor_sequence_dict[specie])
            raise ValueError()
            
            for possible_local_sequence in itertools.permutations(unsorted_neighbor_info.neighbor_species_sequence_dict[specie]):
                
                if np.allclose(self.build_distance_matrix_from_getnninfo_output(possible_local_sequence),self.neighbor_species_distance_matrix_dict[specie],rtol=rtol,atol=atol):
                    
                    sorted_neighbor_sequence_dict[specie].append(list(possible_local_sequence))
            
            if len(sorted_neighbor_sequence_dict[specie])==0:
                raise ValueError("no sorted sequence found for "+str(specie)+" please check if the rtol or atol is too small")
            
        #neighbor_info_logger.warning(str(sorted_neighbor_sequence_dict))
        
        
        sorted_neighbor_sequence_list=[]
        
        for specie in sorted_neighbor_sequence_dict:
            sorted_neighbor_sequence_list.append(sorted_neighbor_sequence_dict[specie])
        
        

        if find_nearest_if_fail:
            closest_smilarity_score=999999.0
            closest_sequence=[]
            for possible_complete_sequence in itertools.product(*sorted_neighbor_sequence_list):
                
  
                re_sorted_neighbors_list=[]
                
                for neighbor in possible_complete_sequence:

                    re_sorted_neighbors_list.extend(list(neighbor))               
            
                this_smilarity_score=np.sum(np.abs(self.build_distance_matrix_from_getnninfo_output(re_sorted_neighbors_list)-self.distance_matrix))
                
                if this_smilarity_score<closest_smilarity_score:
                    closest_smilarity_score=this_smilarity_score
                    closest_sequence=re_sorted_neighbors_list
                    
            neighbor_info_logger.warning("the closest neighbor_info identified. Total difference"+str(closest_smilarity_score))
            neighbor_info_logger.info("new sorting is found,new distance matrix is ")
            neighbor_info_logger.info(str(self.build_distance_matrix_from_getnninfo_output(closest_sequence)))
            neighbor_info_logger.info("The differece matrix is : \n")
            neighbor_info_logger.info(str(self.build_distance_matrix_from_getnninfo_output(closest_sequence)-self.distance_matrix))                            
            return closest_sequence
                
            
      
        else:
        
            for possible_complete_sequence in itertools.product(*sorted_neighbor_sequence_list):
                
                #neighbor_info_logger.warning(str(possible_complete_sequence))
                
                re_sorted_neighbors_list=[]
                
                for neighbor in possible_complete_sequence:

                    re_sorted_neighbors_list.extend(list(neighbor))               
            
                if np.allclose(self.build_distance_matrix_from_getnninfo_output(re_sorted_neighbors_list),self.distance_matrix,rtol=rtol,atol=atol):
                    neighbor_info_logger.info("new sorting is found,new distance matrix is ")
                    neighbor_info_logger.info(str(self.build_distance_matrix_from_getnninfo_output(re_sorted_neighbors_list)))
                    neighbor_info_logger.warning("The differece matrix is : \n")
                    neighbor_info_logger.info(str(self.build_distance_matrix_from_getnninfo_output(re_sorted_neighbors_list)-self.distance_matrix))                
                    
                    return re_sorted_neighbors_list
  
            raise ValueError("sequence not founded!")                
  
  


        
  
generate_events3(prim_cif_name=prim_cif_name,local_env_cutoff_dict=local_env_cutoff_dict,mobile_ion_identifier_type=mobile_ion_identifier_type,mobile_ion_specie_1_identifier=mobile_ion_specie_1_identifier,mobile_ion_specie_2_identifier=mobile_ion_specie_2_identifier,species_to_be_removed=["O2-","O","Co+","Co"],distance_matrix_rtol=0.01,distance_matrix_atol=0.01,find_nearest_if_fail=False,convert_to_primitive_cell=False,export_local_env_structure=True,supercell_shape=[2,2,2],event_fname="events.json",event_kernal_fname='event_kernal.csv',verbosity="INFO")

Extracting clusters from primitive cell structure. This primitive cell should be bulk structure, grain boundary model not implemented yet.
/Users/weihangxie/Documents/GitHub/kmcPy_dev/kmcpy/external/pymatgen_cif.py:1498: UserWarning: Issues encountered while parsing CIF: Some fractional coordinates rounded to ideal values to avoid issues with finite precision.
  warnings.warn("Issues encountered while parsing CIF: %s" % "\n".join(self.warnings))
primitive cell composition after adding oxidation state and removing uninvolved species: 
Na+6 Li+3
building mobile_ion_specie_1 index list
please check if these are mobile_ion_specie_1:
[0.         0.         4.68453333] Na+
[0.         0.         9.36906667] Na+
[1.40805    0.81293805 9.36906667] Na+
[1.40805000e+00 8.12938047e-01 1.72436393e-16] Na+
[1.63130620e-16 1.62587609e+00 1.72436393e-16] Na+
[1.63130620e-16 1.62587609e+00 4.68453333e+00] Na+
start finding the neighboring sequence of mobile_ion_specie_1s
total number of mobile_ion_spe

KeyboardInterrupt: 