# Test on $LiCoO_2$

First We will have to add a dummy atom in the center of 3-Li-triangle, as the center of cluster expansion

In [2]:
from kmcpy.external.pymatgen_structure import Structure
LiCoO2=Structure.from_cif("EntryWithCollCode51182.cif")
LiCoO2.make_supercell([2,2,1])
import numpy as np
#np.set_printoptions(precision=2)
for site in LiCoO2:
    if "Li+" in site:
        print(site,site.properties,site.frac_coords)
print(LiCoO2)


[0. 0. 0.] Li+ {'wyckoff_sequence': 0, 'local_index': 0, 'label': 'Li1'} [0. 0. 0.]
[-1.40805000e+00  2.43881414e+00  1.72436393e-16] Li+ {'wyckoff_sequence': 0, 'local_index': 0, 'label': 'Li1'} [0.  0.5 0. ]
[2.81610000e+00 0.00000000e+00 1.72436393e-16] Li+ {'wyckoff_sequence': 0, 'local_index': 0, 'label': 'Li1'} [0.5 0.  0. ]
[1.40805000e+00 2.43881414e+00 3.44872785e-16] Li+ {'wyckoff_sequence': 0, 'local_index': 0, 'label': 'Li1'} [0.5 0.5 0. ]
[1.40805    0.81293805 4.68453333] Li+ {'wyckoff_sequence': 1, 'local_index': 1, 'label': 'Li1'} [0.33333333 0.16666667 0.33333333]
[-1.17827970e-16  3.25175219e+00  4.68453333e+00] Li+ {'wyckoff_sequence': 1, 'local_index': 1, 'label': 'Li1'} [0.33333333 0.66666667 0.33333333]
[4.22415    0.81293805 4.68453333] Li+ {'wyckoff_sequence': 1, 'local_index': 1, 'label': 'Li1'} [0.83333333 0.16666667 0.33333333]
[2.8161     3.25175219 4.68453333] Li+ {'wyckoff_sequence': 1, 'local_index': 1, 'label': 'Li1'} [0.83333333 0.66666667 0.33333333]
[

Here the 1st, 3rd, 4th Li+ obviously form a triangle, refer to Anton's paper (Van Der Ven A, Ceder G. Lithium migration in layered LixCoO2 Electrochemical and Solid-State Letters. 3: 301-304. DOI: 10.1149/1.1391130), the center of local cluster expansion is the center of such Lithium triangle. Then we need to add an dummy atom in the center for events generator

In [3]:
from kmcpy.external.pymatgen_structure import Structure
import numpy

def add_dummy(structure1,structure2,site1,site2,site3):
    structure1.append(species="Na+",coords=(structure2[site1].coords+structure2[site2].coords+structure2[site3].coords)/3,coords_are_cartesian=True,properties={'local_index':0, 'label': 'dummy'})

LiCoO2_2=Structure.from_cif("EntryWithCollCode51182.cif")

for center_Li in [[0,2,3],[0,1,3],[4,6,7],[4,5,7],[8,10,11],[8,9,11]]:
    add_dummy(LiCoO2_2,LiCoO2,*center_Li)

print(LiCoO2_2)
LiCoO2_2.to("cif","LiCoO2_dummy_added.cif",symprec=0.01)

Full Formula (Na6 Li3 Co3 O6)
Reduced Formula: Na2LiCoO2
abc   :   2.816100   2.816100  14.053600
angles:  90.000000  90.000000 120.000000
Sites (18)
  #  SP           a         b         c  label      local_index    wyckoff_sequence
---  ----  --------  --------  --------  -------  -------------  ------------------
  0  Li+   0         0         0         Li1                  0                   0
  1  Li+   0.666667  0.333333  0.333333  Li1                  1                   1
  2  Li+   0.333333  0.666667  0.666667  Li1                  2                   2
  3  Co3+  0         0         0.5       Co1                  3                   0
  4  Co3+  0.666667  0.333333  0.833333  Co1                  4                   1
  5  Co3+  0.333333  0.666667  0.166667  Co1                  5                   2
  6  O2-   0         0         0.76049   O1                   6                   0
  7  O2-   0         0         0.23951   O1                   7                   1
  8  O2-  

In [4]:
mobile_ion_identifier_type="label"
mobile_ion_specie_1_identifier="Na0"
mobile_ion_specie_2_identifier="Li1"
prim_cif_name="LiCoO2_dummy_added.cif"
local_env_cutoff_dict={('Na+','Li+'):4.31}
from kmcpy.event_generator import generate_events3
generate_events3(prim_cif_name=prim_cif_name,local_env_cutoff_dict=local_env_cutoff_dict,mobile_ion_identifier_type=mobile_ion_identifier_type,mobile_ion_specie_1_identifier=mobile_ion_specie_1_identifier,mobile_ion_specie_2_identifier=mobile_ion_specie_2_identifier,species_to_be_removed=["O2-","O","Co+","Co"],distance_matrix_rtol=0.01,distance_matrix_atol=0.01,find_nearest_if_fail=False,convert_to_primitive_cell=False,export_local_env_structure=True,supercell_shape=[2,2,2],event_fname="events.json",event_kernal_fname='event_kernal.csv',verbosity="INFO")

Extracting clusters from primitive cell structure. This primitive cell should be bulk structure, grain boundary model not implemented yet.
/Users/weihangxie/Documents/GitHub/kmcPy_dev/kmcpy/external/pymatgen_cif.py:1498: UserWarning: Issues encountered while parsing CIF: Some fractional coordinates rounded to ideal values to avoid issues with finite precision.
  warnings.warn("Issues encountered while parsing CIF: %s" % "\n".join(self.warnings))
primitive cell composition after adding oxidation state and removing uninvolved species: 
Na+6 Li+3
building mobile_ion_specie_1 index list
please check if these are mobile_ion_specie_1:
[0.         0.         4.68453333] Na+
[0.         0.         9.36906667] Na+
[1.40805    0.81293805 9.36906667] Na+
[1.40805000e+00 8.12938047e-01 1.72436393e-16] Na+
[1.63130620e-16 1.62587609e+00 1.72436393e-16] Na+
[1.63130620e-16 1.62587609e+00 4.68453333e+00] Na+
start finding the neighboring sequence of mobile_ion_specie_1s
total number of mobile_ion_spe

Saving: events.json
Generating event kernal ...
Saving into: event_kernal.csv


{(('Li+', 12),): <kmcpy.event_generator.neighbor_info_matcher at 0x150391820>}

In [5]:
mobile_ion_identifier_type="label"
mobile_ion_specie_1_identifier="Na0"
mobile_ion_specie_2_identifier="Li1"
prim_cif_name="LiCoO2_dummy_added.cif"
local_env_cutoff_dict={('Na+','Li+'):4.31}

  
generate_events3(prim_cif_name=prim_cif_name,local_env_cutoff_dict=local_env_cutoff_dict,mobile_ion_identifier_type=mobile_ion_identifier_type,mobile_ion_specie_1_identifier=mobile_ion_specie_1_identifier,mobile_ion_specie_2_identifier=mobile_ion_specie_2_identifier,species_to_be_removed=["O2-","O","Co+","Co"],distance_matrix_rtol=0.01,distance_matrix_atol=0.01,find_nearest_if_fail=False,convert_to_primitive_cell=False,export_local_env_structure=True,supercell_shape=[2,2,2],event_fname="events.json",event_kernal_fname='event_kernal.csv',verbosity="INFO")

Extracting clusters from primitive cell structure. This primitive cell should be bulk structure, grain boundary model not implemented yet.
Extracting clusters from primitive cell structure. This primitive cell should be bulk structure, grain boundary model not implemented yet.
/Users/weihangxie/Documents/GitHub/kmcPy_dev/kmcpy/external/pymatgen_cif.py:1498: UserWarning: Issues encountered while parsing CIF: Some fractional coordinates rounded to ideal values to avoid issues with finite precision.
  warnings.warn("Issues encountered while parsing CIF: %s" % "\n".join(self.warnings))
primitive cell composition after adding oxidation state and removing uninvolved species: 
primitive cell composition after adding oxidation state and removing uninvolved species: 
Na+6 Li+3
Na+6 Li+3
building mobile_ion_specie_1 index list
building mobile_ion_specie_1 index list
please check if these are mobile_ion_specie_1:
[0.         0.         4.68453333] Na+
[0.         0.         9.36906667] Na+
[1.408

Saving: events.json
Generating event kernal ...
Saving into: event_kernal.csv


{(('Li+', 12),): <kmcpy.event_generator.neighbor_info_matcher at 0x11c8bdf10>}