no sys args version, for debug purpose

Following block is a script for running KMC, just run it see if it works


In [1]:
#!/usr/bin/env python

from kmcpy.io import InputSet,load_occ
from kmcpy.kmc import KMC
import os
import sys

def main(api=1,**kwargs):
    inputset=InputSet.from_json("test_input.json")

    print(inputset._parameters.keys())
    inputset.parameter_checker()

    if api==1:


        inputset.set_parameter("occ",load_occ(inputset._parameters["mc_results"],inputset._parameters["supercell_shape"]))
        # step 1 initialize global occupation and conditions
        kmc = KMC()
        events_initialized = kmc.initialization(**inputset._parameters) # v in 10^13 hz

        # # step 2 compute the site kernal (used for kmc run)
        kmc.load_site_event_list(inputset._parameters["event_kernel"])

        # # step 3 run kmc
        kmc.run_from_database(events=events_initialized,**inputset._parameters)
    if api>1:
        raise NotImplementedError
    pass


if __name__ == "__main__":
    
    main()


dict_keys(['v', 'equ_pass', 'kmc_pass', 'supercell_shape', 'fitting_results', 'fitting_results_site', 'lce_fname', 'lce_site_fname', 'prim_fname', 'event_fname', 'event_kernel', 'mc_results', 'T', 'comp', 'structure_idx', 'api'])
Initializing kMC calculations with pirm.json at ./inputs/prim.json ...
Supercell Shape:
 [[2 0 0]
 [0 1 0]
 [0 0 1]]
Converting supercell ...
Loading fitting results ...
Loading fitting results (site energy) ...
Loading occupation: [-1 -1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1 -1  1 -1  1 -1 -1  1 -1 -1 -1
 -1 -1 -1 -1]
Fitted time and error (LOOCV,RMS)
01/21/2022, 16:49:17 149.8671381416 29.1495050791
Fitted KECI and empty cluster
[10.5029085379, 4.0803809727, 0.0, 0.0, -11.2639080302, 0.0, -4.0578126572, 0.0, -7.2124075988, 0.0, 0.0, 0.0, 0.0] 339.1083600548
Fitted time and error (LOOCV,RMS) (site energy)
01/21/2022, 16:49:17 149.8671381416 29.1495050791
Fitted KECI and empty cluster (site energy)
[10.5029085379, 4.0803809727, 0.0, 0.0, -11.2639080302, 0.0, -4.

/userhome1/david/repo/kmcPy/kmcpy/tracker.py:93: RuntimeWarning: invalid value encountered in true_divide
  corr_factor = np.linalg.norm(self.displacement,axis=1)**2/(self.hop_counter*a**2)


23	3.179E-06	1.244E+02	3.379E-09	6.521E-10	2.730E-01	1.930E-01	2.895E-01	0.29	0.24
24	3.210E-06	1.243E+02	3.444E-09	6.454E-10	2.783E-01	1.874E-01	2.763E-01	0.29	0.24
25	3.269E-06	1.267E+02	3.605E-09	6.460E-10	2.913E-01	1.792E-01	2.741E-01	0.29	0.24
26	3.369E-06	1.506E+02	4.273E-09	7.449E-10	3.454E-01	1.743E-01	3.277E-01	0.29	0.24
27	3.407E-06	1.467E+02	4.153E-09	7.178E-10	3.357E-01	1.728E-01	3.111E-01	0.29	0.24
28	3.485E-06	1.450E+02	3.711E-09	6.937E-10	2.999E-01	1.869E-01	3.010E-01	0.29	0.24
29	3.523E-06	1.450E+02	3.671E-09	6.861E-10	2.967E-01	1.869E-01	2.973E-01	0.29	0.24
30	3.615E-06	1.450E+02	3.577E-09	6.687E-10	2.891E-01	1.869E-01	2.934E-01	0.29	0.24
31	3.731E-06	1.451E+02	3.859E-09	6.483E-10	3.119E-01	1.680E-01	2.956E-01	0.29	0.24
32	3.803E-06	1.590E+02	4.321E-09	6.967E-10	3.492E-01	1.612E-01	3.104E-01	0.29	0.24
33	3.849E-06	1.616E+02	4.317E-09	6.996E-10	3.489E-01	1.620E-01	3.007E-01	0.29	0.24
34	3.929E-06	1.556E+02	3.893E-09	6.601E-10	3.146E-01	1.696E-01	2.866E-01	0.29	0.24
35	3

following block is for generating the local cluster expansion


In [2]:
from kmcpy.model import LocalClusterExpansion

a=LocalClusterExpansion()
a.initialization()
a.to_json("testoutput.json")

Searching local env around [ 0.      0.     11.0905] Na ...
793 clusters will be generated ...

Generating possible clusters within this diffusion unit...
Cutoffs: pair = 6 Angst, triplet = 6 Angst, quadruplet = 6 Angst
Type	Index	max_length	min_length	Point Group	Multiplicity
point	(0,)      	   0.000	   0.000	Kh   	    6
point	(6,)      	   0.000	   0.000	Kh   	    6
pair 	(0, 1)    	   4.727	   4.727	D*h  	    6
pair 	(0, 3)    	   5.103	   5.103	D*h  	    6
pair 	(0, 6)    	   3.710	   3.710	C*v  	    6
pair 	(0, 7)    	   3.056	   3.056	C*v  	    6
pair 	(0, 8)    	   3.162	   3.162	C*v  	    6
pair 	(6, 7)    	   4.922	   4.922	D*h  	    6
pair 	(6, 9)    	   5.629	   5.629	D*h  	    6
triplet	(0, 1, 2) 	   5.103	   4.727	C2v  	    6
triplet	(0, 1, 6) 	   4.727	   3.162	Cs   	    6
triplet	(0, 1, 7) 	   4.727	   3.056	Cs   	    6
triplet	(0, 3, 4) 	   5.103	   5.103	D3h  	    2
triplet	(0, 3, 7) 	   5.103	   3.056	C2v  	    6
triplet	(0, 6, 7) 	   4.922	   3.056	Cs   	    6
tripl